apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
  name: jvb-udp
  namespace: jitsi
spec:
  selector:
    app: jitsi-videobridge2
  externalTrafficPolicy: Cluster
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 100
  type: NodePort
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
    name: udp1
  - port: 443
    protocol: TCP
    targetPort: 443
    nodePort: 30301
    name: tcp1
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: 30302
    name: tcp2