---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: jitsi-hpa
  namespace: jitsi
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jitsi
  minReplicas: 50
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
status:
  observedGeneration: 1
  currentReplicas: 50
  desiredReplicas: 50
  currentMetrics:
  - type: Resource
    resource:
      name: cpu
      current:
        averageUtilization: 0
        averageValue: 0
