---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-server-pv
  namespace: jitsi
#  pv.beta.kubernetes.io/gid: "1000"
spec:
  storageClassName: jitsi-videobridge-configuration
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.99.1
    path: "/data"
    readOnly: false