---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-server-pvc
  namespace: jitsi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: jitsi-videobridge-configuration
  resources:
    requests:
      storage: 20Gi
